Covid19CharitySystem/Controllers/AdminController.cs
using Covid19CharitySystem.BL;
using Covid19CharitySystem.DAL;
using Covid19CharitySystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;

namespace Covid19CharitySystem.Controllers
{
    public class AdminController : Controller
    {
        // GET: Admin
        public ActionResult Index()
        {
            if (Session["AdminId"]==null)
            {
                return RedirectToAction("Login","Home");
            }
            ViewBag.volunteers = new UserBL().getUserList().Where(x => x.Role == 3).Count();
            ViewBag.donors = new UserBL().getUserList().Where(x => x.Role == 2).Count();
            ViewBag.donations = new UserBL().getDonationList().Count();
            return View();
        }
        public ActionResult Volunteers()
        {
            if (Session["AdminId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<User> volunteers = new UserDAL().getUsersList().Where(x => x.Role == 3).ToList();
            return View(volunteers);
        }
        public ActionResult Donors()
        {
            if (Session["AdminId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<User> donors = new UserDAL().getUsersList().Where(x => x.Role == 2).ToList();

            return View(donors);
        }
        public ActionResult RecentDonations()
        {
            if (Session["AdminId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<Donation> list = new UserDAL().getDonationsList().Where(x => x.IsAssigned == 0).ToList();
            return View(list);
        }
        public ActionResult CollectedDonations()
        {
            if (Session["AdminId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<Donation> list = new UserDAL().getDonationsList().Where(x => x.IsAssigned !=0).ToList();
            return View(list);
        }
        public ActionResult AssignTask(int Did,string Dtype,string Dloc)
        {
            if (Session["AdminId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.donationId = Did;
            ViewBag.donationType = Dtype;
            ViewBag.donationLoc = Dloc;
            ViewBag.volunteers = new UserBL().getUserList().Where(x => x.Role == 3).ToList();
            return View();
        }
        [HttpPost]
        public ActionResult PostTask(Task obj)
        {
            bool temp = new UserBL().AddTask(obj);
            if (temp)
            {
                User vol = new UserBL().getUserById(obj.User_Id);
               
                Donation don = new UserBL().getDonationById(obj.Donation_Id);
                string note = obj.Note == "" ? "Nothing to say." : obj.Note;
                sendEmail(vol.Email,don.Type,don.PickLocation,note);
                Donation donate = new Donation()
                {
                    Id = don.Id,
                    CreatedAt = don.CreatedAt,
                    IsAssigned = obj.User_Id,
                    PickLocation = don.PickLocation,
                    Type = don.Type,
                    User_Id = don.User_Id,
                    Status = 0
                };
                new UserBL().UpdateDonation(donate);
            }
            return RedirectToAction("RecentDonations");
        }

        public JsonResult BlockUser(int id,int status)
        {
            User user = new UserBL().getUserById(id);
            User _user = new User()
            {
                Address = user.Address,
                CreatedAt = user.CreatedAt,
                Email = user.Email,
                Id = user.Id,
                IsActive = status,
                Name = user.Name,
                Password = user.Password,
                Phone = user.Phone,
                Role = user.Role
            };

            bool temp = new UserBL().UpdateUser(_user);
            if (temp)
                return Json(1);
            return Json(-1);
        }
        public bool sendEmail(string email,string type,string loc,string note)
        {
            try
            {
                MailMessage mail = new MailMessage();
                mail.To.Add(email);
                mail.From = new MailAddress("no-reply@covid19charitysystem.com");
                mail.Subject = "Task Assignment";
                string Body = "<p><html><body>Dear Volunteer! <br /><br />A new task has been assigned to you.<br />Please complete your task as soon as possible.<br /> <b>Donation Type: </b> "+type+"<br/><b>Pick Up Location: </b>"+loc+"<br/><b>Note:</b><br/>"+note+"<br/>Thanks<br /> Team Covid19CharitySystem </body></html></p>";
                mail.Body = Body;
                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = new System.Net.NetworkCredential("aqsajamil0198@gmail.com", "aqsa1234"); // Enter seders User name and password   
                smtp.EnableSsl = true;
                smtp.Send(mail);
                return true;
            }
            catch (Exception ex)
            {
                return false;
            }
        }
    }
}

Covid19CharitySystem/Controllers/DonorController.cs
using Covid19CharitySystem.BL;
using Covid19CharitySystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Covid19CharitySystem.Controllers
{
    public class DonorController : Controller
    {
        // GET: Donor
        public ActionResult Index()
        {
            if (Session["DonorId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.allDonations = new UserBL().getDonationList().Where(x => x.User_Id == Convert.ToInt32(Session["DonorId"])).Count();
            return View();
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            Session["Name"] = null;
            return RedirectToAction("Index","Home");
        }
        public ActionResult AddDonation()
        {
            if (Session["DonorId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            return View();
        }
        [HttpPost]
        public ActionResult PostDonation(Donation donate)
        {
            donate.User_Id = Convert.ToInt32(Session["DonorId"]);
            bool temp = new UserBL().AddDonation(donate);
            return RedirectToAction("PreviousDonations");
        }
        public ActionResult PreviousDonations()
        {
            if (Session["DonorId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            List<Donation> list = new UserBL().getDonationList();
            return View(list);
        }
        public JsonResult RemoveDonation(int dId)
        {
            bool temp = new UserBL().DeleteDonation(dId);
            if (temp)
                return Json(1);
            return Json(-1);
        }
    }
}

Covid19CharitySystem/Controllers/VolunteerController.cs
using Covid19CharitySystem.BL;
using Covid19CharitySystem.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace Covid19CharitySystem.Controllers
{
    public class VolunteerController : Controller
    {
        // GET: Volunteer
        public ActionResult Index()
        {
            if (Session["volunteerId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            ViewBag.newtask = new UserBL().getTaskList().Where(x => x.User_Id == Convert.ToInt32(Session["volunteerId"])&&x.Status==0).Count();
            ViewBag.completedtask = new UserBL().getTaskList().Where(x => x.User_Id == Convert.ToInt32(Session["volunteerId"])&&x.Status==1).Count();
            return View();
        }

        public ActionResult TaskList()
        {
            if (Session["volunteerId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int id = Convert.ToInt32(Session["volunteerId"]);
            List<Task> list = new UserBL().getTaskList().Where(x => x.User_Id == id&&x.Status==0).ToList();
            return View(list);

        }
        public ActionResult CompletedTaskList()
        {
            if (Session["volunteerId"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            int id = Convert.ToInt32(Session["volunteerId"]);
            List<Task> list = new UserBL().getTaskList().Where(x => x.User_Id == id && x.Status == 1).ToList();
            return View(list);

        }
        public JsonResult UpdateStatus(int taskId)
        {
            Task task = new UserBL().getTaskById(taskId);
            Task utask = new Task()
            {
                Id = task.Id,
                CreatedAt = task.CreatedAt,
                Note = task.Note,
                Donation_Id = task.Donation_Id,
                IsActive = 1,
                Status = 1,
                User_Id = task.User_Id
            };
           
            bool temp = new UserBL().UpdateTask(utask);
             Donation don = new UserBL().getDonationById(utask.Donation_Id);
            Donation donate = new Donation()
            {
                Id = don.Id,
                CreatedAt = don.CreatedAt,
                IsAssigned =don.IsAssigned,
                PickLocation = don.PickLocation,
                Type = don.Type,
                User_Id = don.User_Id,
                Status = 1
            };
            new UserBL().UpdateDonation(donate);
            if (temp)
                return Json(1);
            return Json(-1);
        }
    }
}

Covid19CharitySystem/Views/Shared/_PanelLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Covid-19 Charity System</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Content/plugins/fontawesome-free/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="~/Content/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Content/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Content/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link href="~/Content/plugins/datatables-buttons/css/buttons.bootstrap4.min.css" rel="stylesheet" />
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Content/dist/css/adminlte.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/Content/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/Content/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
</head>
<body class="hold-transition sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <!-- Messages Dropdown Menu -->
                <!-- Notifications Dropdown Menu -->
                <li class="nav-item dropdown">
                    <a class="nav-link" data-toggle="dropdown" href="#">
                        <i class="far fa-user"></i>
                    </a>
                    <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                        <span class="dropdown-item dropdown-header">My Account</span>
                        <div class="dropdown-divider"></div>
                        <a href="@Url.Action("Logout","Donor")" class="dropdown-item">
                            <i class="fas fa-sign-out mr-2"></i> Logout
                        </a>
                    </div>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                <span class="brand-text font-weight-light">Covid-19 Charity System</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                    </div>
                    @{string name = Session["Name"].ToString() == "" ? "Anonymous" : Session["Name"].ToString(); }
                    <div class="info">
                        <a href="#" class="d-block">@name</a>
                    </div>
                </div>


                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        @if (Session["Role"].ToString() == "1")
                        {
                            /**/

                            <li class="nav-item menu-open">
                                <a href="@Url.Action("Index","Admin")" class="nav-link active">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Dashboard
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-copy"></i>
                                    <p>
                                        Manage Users
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="@Url.Action("Volunteers","Admin")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Volunteers</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("Donors","Admin")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Donors</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-copy"></i>
                                    <p>
                                        Manage Donations
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="@Url.Action("RecentDonations","Admin")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Recent Donations</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("CollectedDonations","Admin")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Collected Donations</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                        }
                        else if (Session["Role"].ToString() == "2")
                        {
                            /**/

                            <li class="nav-item menu-open">
                                <a href="@Url.Action("Index","Donor")" class="nav-link active">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Dashboard
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-copy"></i>
                                    <p>
                                        Donation Options
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="@Url.Action("AddDonation","Donor")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Add Donation</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("PreviousDonations","Donor")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Previous Donations</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>

                        }
                        else
                        {
                            <li class="nav-item menu-open">
                                <a href="@Url.Action("Index","Volunteer")" class="nav-link active">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Dashboard
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="#" class="nav-link">
                                    <i class="nav-icon fas fa-copy"></i>
                                    <p>
                                        Manage Tasks
                                        <i class="fas fa-angle-left right"></i>
                                    </p>
                                </a>
                                <ul class="nav nav-treeview">
                                    <li class="nav-item">
                                        <a href="@Url.Action("TaskList","Volunteer")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>New Tasks</p>
                                        </a>
                                    </li>
                                    <li class="nav-item">
                                        <a href="@Url.Action("CompletedTaskList","Volunteer")" class="nav-link">
                                            <i class="far fa-circle nav-icon"></i>
                                            <p>Completed Tasks</p>
                                        </a>
                                    </li>
                                </ul>
                            </li>
                        }
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>


        @RenderBody()

        <!-- Main Footer -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2020.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.1.0-pre
            </div>
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/Content/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Content/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="~/Content/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.js"></script>
    <!-- Select2 -->
    <script src="~/Content/plugins/select2/js/select2.full.min.js"></script>
    <!-- PAGE ~/Content/plugins -->
    <!-- jQuery Mapael -->
    <script src="~/Content/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
    <script src="~/Content/plugins/raphael/raphael.min.js"></script>
    <script src="~/Content/plugins/jquery-mapael/jquery.mapael.min.js"></script>
    <script src="~/Content/plugins/jquery-mapael/maps/usa_states.min.js"></script>
    <!-- ChartJS -->
    <script src="~/Content/plugins/chart.js/Chart.min.js"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Content/dist/js/pages/dashboard2.js"></script>
    <!-- DataTables -->
    <script src="~/Content/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Content/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Content/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Content/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/Content/plugins/datatables-buttons/js/buttons.html5.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Content/dist/js/adminlte.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    <script src="~/Content/dist/js/demo.js"></script>
    <!-- Page specific script -->
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true,
                "autoWidth": false,
                buttons: [
                    'csv', 'excel', 'pdf', 'print'
                ]
            });
            //Initialize Select2 Elements
            $('.select2').select2()
        });
    </script>
</body>
</html >